### ISSUE TITLE
remove-linked-list-elements似乎可以写的更简单

### ISSUE THREAD

**Issue by ir193** [MaskRay/LeetCode#1]
https://github.com/ir193/LeetCode/commit/0602dca2fe9758cfae9f9a910b556ea0976b3cfd
宋教授求指点！我这样写可以只用两个指针，OJ上是全过了的
听说一言不合PR不礼貌

**Comment by MaskRay** [comment]
这是个 issue 不是 PR?

**Comment by MaskRay** [comment]
赞……自行创建了一个PR合并了
